{
 "title": "Example",
 "time": { "from": "now-10m", "to": "now+10h" },
 "refresh": "5s",
 "panels": [
  {
   "title": "lasers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  count,\n  cycle,\n  state\nFROM lasers\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cdh",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  battery,\n  count,\n  temp\nFROM cdh\nORDER BY 1"
    }
   ]
  },
  {
   "title": "detector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  count,\n  cycle,\n  range,\n  state\nFROM detector\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  }
 ]
}